name: Continuous Integration

on:
  pull_request:

jobs:
  lint:
    name: 👮 Lint & Typecheck
    runs-on: ubuntu-latest
    env:
      GQL_HOST: https://api-6zdezivzkq-ey.a.run.app
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun biome ci
      - run: bun nuxt typecheck
