name: Continuous Integration

on:
  pull_request:

jobs:
  lint:
    name: 👮 Lint & Typecheck
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: software
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install
      - run: bun biome ci
      - run: bun nuxt typecheck
