name: 📦Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE }}
          release-type: simple

# TODO Add artifact to release
#      - name: Package build artifacts
#        id: package
#        run: |
#          ARTIFACT="artifact.tar.gz"
#          tar -czf "$ARTIFACT" .output
#          echo "artifact=$ARTIFACT" >> "$GITHUB_OUTPUT"
#      - name: Generate a changelog
#        uses: orhun/git-cliff-action@v4
#        id: git-cliff
#        with:
